In [10]:
import pandas as pd
import numpy as np

In [11]:
data1 = pd.read_csv('data/round1/prices_round_1_day_-2.csv', header = 0, sep=";")
data2 = pd.read_csv('data/round1/prices_round_1_day_-1.csv', header = 0, sep=";")
data3 = pd.read_csv('data/round1/prices_round_1_day_0.csv', header = 0, sep=";")

In [25]:
print(data1.head())
print(data3.tail())

#creating midprice differences matrix

data = pd.concat([data1,data2, data3])

midprices_column = data.loc[:, "mid_price"]
starfruit_midprices = midprices_column[data["product"] == "STARFRUIT"]
print(starfruit_midprices.head())
#print(starfruit_midprices.tail())

delta_starfruit_midprices = starfruit_midprices.diff()
print(delta_starfruit_midprices.head())

delta_starfruit_midprices_np = delta_starfruit_midprices.to_numpy()

delta_matrix = delta_starfruit_midprices_np.reshape(-1,4)
delta_matrix = delta_matrix[1:] #remove first row as it contains NaN
X = delta_matrix


"""ones_column = np.ones((delta_matrix.shape[0],1))
X = np.hstack((ones_column, delta_matrix))
print(X[:5, :])
print(X.shape)""" #don't need the ones column as beta constant term should be zero




   day  timestamp    product  bid_price_1  bid_volume_1  bid_price_2  \
0   -2          0  AMETHYSTS         9996             1       9995.0   
1   -2          0  STARFRUIT         4997            26          NaN   
2   -2        100  AMETHYSTS        10000             5       9995.0   
3   -2        100  STARFRUIT         5000             5       4998.0   
4   -2        200  STARFRUIT         4997             1       4996.0   

   bid_volume_2  bid_price_3  bid_volume_3  ask_price_1  ask_volume_1  \
0          25.0          NaN           NaN        10004             1   
1           NaN          NaN           NaN         5003            26   
2          20.0          NaN           NaN        10005            20   
3           6.0       4997.0          20.0         5004            20   
4          30.0          NaN           NaN         5003            31   

   ask_price_2  ask_volume_2  ask_price_3  ask_volume_3  mid_price  \
0      10005.0          25.0          NaN           NaN   

In [21]:
# Assuming 'array' is your NumPy array
# For demonstration, let's create a sample array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Create a column vector of ones
ones_column = np.ones((array.shape[0], 1))

# Add the column of ones to the left of the original array
array_with_ones = np.hstack((ones_column, array))

print(array_with_ones)

[[1. 1. 2. 3.]
 [1. 4. 5. 6.]
 [1. 7. 8. 9.]]


In [15]:
#doing linear regression on the matrix

def LinearRegression(data):

    midprices_column = data.loc[:, "mid_price"]
    starfruit_midprices = midprices_column[data["product"] == "STARFRUIT"]

    delta_starfruit_midprices = starfruit_midprices.diff()

    delta_starfruit_midprices_np = delta_starfruit_midprices.to_numpy()

    delta_matrix = delta_starfruit_midprices_np.reshape(-1,4)
    delta_matrix = delta_matrix[1:] #remove first row as it contains NaN
    X = delta_matrix

    y = #delta midprice at next timestamp

    beta = np.linalg.lstsq(X, y,rcond=None)[0]

    fit = X.dot(beta)
  
    residuals = data_matrix[:,1] - fit

    return [beta, fit, residuals]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
