In [100]:
import pandas as pd
import numpy as np

In [101]:
data1 = pd.read_csv('../prices/prices_round_1_day_-2.csv', header = 0, sep=";")
data2 = pd.read_csv('../prices/prices_round_1_day_-1.csv', header = 0, sep=";")
data3 = pd.read_csv('../prices/prices_round_1_day_0.csv', header = 0, sep=";")

In [102]:
#print(data1.head())
#print(data3.tail())

#creating midprice differences matrix

data = pd.concat([data1,data2, data3])
data = data[data["product"] == "STARFRUIT"]




data = data.fillna(0)

#vwap = (data["bid_price_1"]*data["bid_volume_1"] + data["bid_price_2"]*data["bid_volume_2"] + data["bid_price_3"]*data["bid_volume_3"] + data["ask_price_1"]*data["ask_volume_1"] + data["ask_price_2"]*data["ask_volume_2"] + data["ask_price_3"]*data["ask_volume_3"])/(data["ask_volume_3"]+data["ask_volume_2"]+data["ask_volume_1"]+data["bid_volume_3"]+data["bid_volume_3"]+data["bid_volume_2"]+data["bid_volume_1"])

sum = 0
volsum = 0 
for i in range(1,3):
   
    sum += data[f'bid_price_{i}'] * data[f'bid_volume_{i}'] + data[f'ask_price_{i}'] * data[f'ask_volume_{i}']
    volsum += data[f'bid_volume_{i}'] + data[f'ask_volume_{i}']

print(sum[:5])

vwap = sum/volsum
vwap = vwap.to_numpy()

dmatrix = vwap.reshape(-1,4)
matrix = vwap[1:] #remove first row as we don't want to predict it
X = dmatrix[:-1]
print(X[25:])

y = dmatrix[1:,0]
print(y[5:])

print(y.shape)
print(X.shape)






1    260000.0
3    155068.0
4    309970.0
7    269973.0
9    199940.0
dtype: float64
[[4999.5        4998.44642857 4998.51666667 4999.53191489]
 [4999.5        4999.5        5000.59375    5000.5       ]
 [5000.5        5001.5        5000.5        5001.5       ]
 ...
 [5052.5        5052.37704918 5053.5        5053.70588235]
 [5053.5        5052.51724138 5052.36842105 5051.54166667]
 [5049.57142857 5051.34482759 5051.5        5052.5       ]]
[5000.5        5000.5        4999.5        ... 5053.5        5049.57142857
 5050.26153846]
(7499,)
(7499, 4)


In [103]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

lr = LinearRegression()
lr.fit(X, y)

# Coefficients
print("Coefficients:", lr.coef_)
print("Intercept:", lr.intercept_)

predictions = lr.predict(X)
mse = mean_squared_error(y, predictions)
print("Mean squared error:", mse)
print("Mean Y squared change:", np.mean(y ** 2))


Coefficients: [0.13583725 0.17354207 0.28468989 0.40577529]
Intercept: 0.7824406885265489
Mean squared error: 1.138027187941819
Mean Y squared change: 25376326.29911834
